---
- name: set system locale
  lineinfile:
    path: /etc/default/locale
    regexp: "^LANG="
    line: "LANG={{ locale }}"

- name: generate locale
  command: "locale-gen {{ locale }}"

- name: set root password
  shell: "echo root:{{ root_password }} | chpasswd"

- name: set root authorized key
  authorized_key:
    key: "{{ root_authorized_key }}"
    user: root
  when: root_authorized_key is defined

- name: install default netplan config
  copy:
    src: dhcp.yaml
    dest: /etc/netplan/dhcp.yaml
    
- name: fix zfs mount ordering
  block:
    - command: "zfs set mountpoint=legacy rpool/var/log"
    - lineinfile:
        path: /etc/fstab
        regexp: "^rpool/var/log"
        line: "rpool/var/log /var/log zfs defaults 0 0"

  