---
- name: configure package sources
  copy:
    src: sources.list
    dest: /etc/apt/sources.list

- name: update package cache
  apt:
    update_cache: yes

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"